package model

type Method string

const (
	DEPOSIT                        Method = "DEPOSIT"
	DEPOSITTEST                           = "DEPOSITTEST"
	DEPOSITWITHADMIN                      = "DEPOSITWITHADMIN"
	QUERYRECEIPT                          = "QUERYRECEIPT"
	QUERYTRANSACTION                      = "QUERYTRANSACTION"
	QUERYTRANSACTIONFROMBLOCKCHAIN        = "QUERYTRANSACTIONFROMBLOCKCHAIN"
	CALLCONTRACT                          = "CALLCONTRACT"
	DEPLOYCONTRACT                        = "DEPLOYCONTRACT"
	CALLWASMCONTRACT                      = "CALLWASMCONTRACT"
	DEPLOYNATIVECONTRACT                  = "DEPLOYNATIVECONTRACT"
	CALLNATIVECONTRACT                    = "CALLNATIVECONTRACT"
	CALLNATIVECONTRACTASYNC               = "CALLNATIVECONTRACTASYNC"
	QUERYBLOCK                            = "QUERYBLOCK"
	QUERYBLOCKBODY                        = "QUERYBLOCKBODY"
	QUERYLASTBLOCK                        = "QUERYLASTBLOCK"
	QUERYBLOCKHEADERINFOSRAW              = "QUERYBLOCKHEADERINFOSRAW"
	CREATEACCOUNT                         = "CREATEACCOUNT"
	FREEZEACCOUNTASYN                     = "FREEZEACCOUNTASYN"
	UNFREEZEACCOUNTASYN                   = "UNFREEZEACCOUNTASYN"
	QUERYACCOUNT                          = "QUERYACCOUNT"
	UPDATECONTRACT                        = "UPDATECONTRACT"
	SIGNHASH                              = "SIGNHASH"
	PARSEOUTPUT                           = "PARSEOUTPUT"

	INVITEUSER = "INVITEUSER"
	NEWCHAIN   = "NEWCHAIN"

	DEPLOYWASMCONTRACT            = "DEPLOYWASMCONTRACT"
	CALLNATIVECONTRACTFORBIZ      = "CALLNATIVECONTRACTFORBIZ"
	CALLNATIVECONTRACTFORBIZASYNC = "CALLNATIVECONTRACTFORBIZASYNC"
	CALLCONTRACTBIZ               = "CALLCONTRACTBIZ"
	DEPLOYCONTRACTFORBIZ          = "DEPLOYCONTRACTFORBIZ"
	QUERYRECEIPTBIZ               = "QUERYRECEIPTBIZ"
	QUERYTRANSACTIONBIZ           = "QUERYTRANSACTIONBIZ"
	UPDATECONTRACTFORBIZ          = "UPDATECONTRACTFORBIZ"
	CALLCONTRACTBIZASYNC          = "CALLCONTRACTBIZASYNC"
	CALLWASMCONTRACTASYNC         = "CALLWASMCONTRACTASYNC"

	GETMYTFINFO        = "GETMYTFINFO"
	GETTAPPINFO        = "GETTAPPINFO"
	INSTALLTAPP        = "INSTALLTAPP"
	EXECUTETAPP        = "EXECUTETAPP"
	EXECUTETAPPPRIVATE = "EXECUTETAPPPRIVATE"

	UPDATERESOURCEMAP = "UPDATERESOURCEMAP"
	GETRESOURCEMAP    = "GETRESOURCEMAP"
	SETRESOURCEMAP    = "SETRESOURCEMAP"

	GETEVENTTOPICBLOCKNUM    = "GETEVENTTOPICBLOCKNUM"
	UPDATEEVENTTOPICBLOCKNUM = "UPDATEEVENTTOPICBLOCKNUM"

	APPLYKEY                 = "APPLYKEY"
	QUERYACCESSLIST          = "QUERYACCESSLIST"
	RESETAPPLYKEY            = "RESETAPPLYKEY"
	QUERYTENANTKMSLIST       = "QUERYTENANTKMSLIST"
	FROZENTENANT             = "FROZENTENANT"
	UNFROZENTENANT           = "UNFROZENTENANT"
	REGISTERBLOCKCHAINCONFIG = "REGISTERBLOCKCHAINCONFIG"
)
